### ISSUE TITLE
Handling suite date variations differently than digital bazaar 

### ISSUE THREAD

**Issue by acarnagey** [transmute-industries/verifiable-data#99]
1. we don't convert to datetime xml format e.g. 2010-10-19T14:47:38-05:00 -> 2010-10-19T19:47:38Z, 2010-10-19T14:47:38.123Z -> 2010-10-19T14:47:38Z, currently it passes the incorrectly formatted date as is
2. we don't error on nonsense strings e.g. foobar -> error, currently it passes the nonsense string as is
3. we don't error on empty strings e.g. "" -> error, currently it gets set to current time
4. we don't pass current time for null e.g. null -> current time, currently it passes epoch time.

**Comment by thomas-tran** [comment]
@OR13 I used the following date when create a credential
const now = new Date();
const issuanceDate = now.toISOString();

Warning occurred
issuanceDate is not valid: [
      "2021-11-04T04:39:10.691Z is not a W3C Date Time.",
      "2021-11-04T04:39:10.691Z could not be converted to unix timestamp and back."
    ]

**Comment by OR13** [comment]
yes, see https://github.com/w3c/vc-data-model/issues/782

The newest version of the spec addresses these warnings, and we will remove them from our codebase when its fully published... which looks like it happened already: https://w3c.github.io/vc-data-model/#issuance-date

beware that some libraries play games with these dates... we're adding lots of date related tests in order to hopefully remove these warnings in the future.

cc @BenjaminMoe feel link your PR or issues.

I hope to one day be able to remove these warnings... IMO, 

```
const issuanceDate = now.toISOString();
```

should still result in a warning since, 

https://www.w3.org/TR/xmlschema11-2/#dateTime

> ISO 8601 describes several formats to define date, times, periods, and recurring dates, with different levels of precision and indetermination. After many discussions, W3C XML Schema selected a subset of these formats and created a primitive datatype for each format that is supported. 

- https://docstore.mik.ua/orelly/xml/schema/ch04_05.htm

The main problem we face is the desire to convert bi-directionally between unix timestamps and XML Date Time... which is what the vc data model is defined in.

That means addressing miliseconds, timezones, etc... consistently... I continue to be troubled by the way dates are handled in the VC Data Model, but at least its getting better.

**Comment by OR13** [comment]
won't be an issue after v2
